### ISSUE TITLE
RFC: should the default CUDA version be upgraded from 8 to 9?

### ISSUE THREAD

**Issue by bcfriesen** [AMReX-Astro/mini-Castro#12]
Currently the default CUDA version that StarLord anticipates is version 8. However, MPI + CUDA codes on summitdev crash at run time if using `nvprof` with CUDA 8. This crash is avoided if one compiles with version 8 but runs with version 9 (the latest available on summitdev). Is there a reason not to change the default compilation version to 9 to fix this problem without requiring the above workaround?

**Comment by maximumcats** [comment]
Yes, we should make this change and compile with CUDA 9 by default.

**Comment by maximumcats** [comment]
Done
